version: '3.9'

services:

  db:
    image: postgres:15-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
